import {
  AlignLeft,
  Box,
  CalendarClock,
  CalendarDays,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ChevronsLeftRight,
  Columns,
  Compass,
  Edit3,
  FileText,
  Images,
  LayoutDashboard,
  LayoutList,
  LayoutPanelLeft,
  ListCollapse,
  ListFilter,
  MenuSquare,
  Minus,
  MousePointerClick,
  Move,
  Navigation,
  PanelLeftClose,
  PanelRightOpen,
  RectangleHorizontal,
  ScrollText,
  Square,
  SquareStack,
  Terminal,
  Braces,
  KeyRound,
  Tag,
  CircleDot,
  ChevronDownSquare,
  SlidersHorizontal,
  ToggleRight,
  AlignJustify,
  SwitchCamera,
  TextCursorInput,
  ToggleLeft,
  MessageSquare,
  AlertTriangle,
  OctagonAlert,
  MessageSquareText,
  Inbox,
  MousePointer,
  MessageCircle,
  Bell,
  Info,
  Palette,
  UserCircle,
  Award,
  BarChart3,
  List,
  Keyboard,
  Loader,
  Boxes,
  LoaderCircle,
  Settings,
  Table,
  BellDot,
} from 'lucide-react';
import type { ComponentCategory } from './type';
export const componentCategories: ComponentCategory[] = [
  {
    name: 'Layout',
    icon: LayoutDashboard,
    components: [
      { type: 'accordion', label: 'Accordion', icon: ListCollapse },
      {
        type: 'aspect-ratio',
        label: 'Aspect Ratio',
        icon: RectangleHorizontal,
      },
      { type: 'card', label: 'Card', icon: Square },
      { type: 'carousel', label: 'Carousel', icon: Images },
      { type: 'collapsible', label: 'Collapsible', icon: PanelLeftClose },
      { type: 'container', label: 'Container', icon: Box },
      { type: 'drawer', label: 'Drawer', icon: PanelRightOpen },
      { type: 'resizable', label: 'Resizable', icon: Move },
      { type: 'scroll-area', label: 'Scroll Area', icon: ScrollText },
      { type: 'separator', label: 'Separator', icon: Minus },
      { type: 'sheet', label: 'Sheet', icon: FileText },
      { type: 'sidebar', label: 'Sidebar', icon: LayoutPanelLeft },
    ],
  },
  {
    name: 'Navigation',
    icon: Compass,
    components: [
      { type: 'breadcrumb', label: 'Breadcrumb', icon: ChevronRight },
      { type: 'command', label: 'Command', icon: Terminal },
      { type: 'context-menu', label: 'Context Menu', icon: MenuSquare },
      { type: 'dropdown-menu', label: 'Dropdown Menu', icon: ChevronDown },
      { type: 'menubar', label: 'Menubar', icon: LayoutList },
      { type: 'navigation-menu', label: 'Navigation Menu', icon: Navigation },
      { type: 'pagination', label: 'Pagination', icon: ChevronsLeftRight },
      { type: 'tabs', label: 'Tabs', icon: Columns },
    ],
  },
  {
    name: 'Forms',
    icon: Edit3,
    components: [
      { type: 'button', label: 'Button', icon: MousePointerClick },
      { type: 'button-group', label: 'Button Group', icon: SquareStack },
      { type: 'calendar', label: 'Calendar', icon: CalendarDays },
      { type: 'checkbox', label: 'Checkbox', icon: CheckSquare },
      { type: 'combobox', label: 'Combobox', icon: ListFilter },
      { type: 'date-picker', label: 'Date Picker', icon: CalendarClock },
      { type: 'field', label: 'Field', icon: AlignLeft },
      { type: 'input', label: 'Input', icon: TextCursorInput },
      { type: 'input-group', label: 'Input Group', icon: Braces },
      { type: 'input-otp', label: 'Input OTP', icon: KeyRound },
      { type: 'label', label: 'Label', icon: Tag },
      { type: 'radio-group', label: 'Radio Group', icon: CircleDot },
      { type: 'select', label: 'Select', icon: ChevronDownSquare },
      { type: 'slider', label: 'Slider', icon: SlidersHorizontal },
      { type: 'switch', label: 'Switch', icon: ToggleRight },
      { type: 'textarea', label: 'TextArea', icon: AlignJustify },
      { type: 'toggle', label: 'Toggle', icon: SwitchCamera },
      { type: 'toggle-group', label: 'Toggle Group', icon: ToggleLeft },
    ],
  },
  {
    name: 'Overlays',
    icon: MessageSquare,
    components: [
      { type: 'alert', label: 'Alert', icon: AlertTriangle },
      { type: 'alert-dialog', label: 'Alert Dialog', icon: OctagonAlert },
      { type: 'dialog', label: 'Dialog', icon: MessageSquareText },
      { type: 'empty', label: 'Empty', icon: Inbox },
      { type: 'hover-card', label: 'Hover Card', icon: MousePointer },
      { type: 'popover', label: 'Popover', icon: MessageCircle },
      { type: 'toast', label: 'Toast', icon: Bell },
      { type: 'tooltip', label: 'Tooltip', icon: Info },
    ],
  },
  {
    name: 'Display',
    icon: Palette,
    components: [
      { type: 'avatar', label: 'Avatar', icon: UserCircle },
      { type: 'badge', label: 'Badge', icon: Award },
      { type: 'chart', label: 'Chart', icon: BarChart3 },
      { type: 'item', label: 'Item', icon: List },
      { type: 'kbd', label: 'Kbd', icon: Keyboard },
      { type: 'progress', label: 'Progress', icon: Loader },
      { type: 'skeleton', label: 'Skeleton', icon: Boxes },
      { type: 'spinner', label: 'Spinner', icon: LoaderCircle },
    ],
  },
  {
    name: 'Other',
    icon: Settings,
    components: [
      { type: 'sonner', label: 'Sonner', icon: BellDot },
      { type: 'table', label: 'Table', icon: Table },
    ],
  },
];
